### ISSUE TITLE
Issue with  'main' entry.

### ISSUE THREAD

**Issue by devzom** [tuarrep/nuxt-twa#3]
I've just installed the plugin, it's already in devDependencies
added it to buildModules and specified the  host 

```
 Module nuxt-twa not found. Please ensure nuxt-twa is in devDependencies and installed. HINT: During build step, for npm/yarn, NODE_ENV=production or --production should NOT be used.


 FATAL  Cannot find module 'nuxt-twa'. Please verify that the package.json has a valid "main" entry

  at new MAIN_NOT_FOUND (node_modules/esm/esm.js:1:217685)
  at zo (node_modules/esm/esm.js:1:223524)
  at $o (node_modules/esm/esm.js:1:224571)
  at xu (node_modules/esm/esm.js:1:226413)
  at wu (node_modules/esm/esm.js:1:227391)
  at Eu (node_modules/esm/esm.js:1:227999)
  at Module.<anonymous> (node_modules/esm/esm.js:1:295976)
  at Resolver.n [as _require] (node_modules/esm/esm.js:1:279589)
  at Resolver.requireModule (node_modules/@nuxt/core/dist/core.js:615:31)
  at ModuleContainer.addModule (node_modules/@nuxt/core/dist/core.js:180:38)


   ╭─────────────────────────────────────────────────────╮
   │                                                     │
   │   ✖ Nuxt Fatal Error                                │
   │                                                     │
   │   Error: Cannot find module 'nuxt-twa'. Please      │
   │   verify that the package.json has a valid "main"   │
   │   entry                                             │
   │                                                     │
   ╰─────────────────────────────────────────────────────╯

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

what's wrong?

**Comment by tuarrep** [comment]
I'll have a look

**Comment by tuarrep** [comment]
I was wrongly released the package. It's now fixed in 0.1.4.

Thanks for reporting 🙏

**Comment by devzom** [comment]
Great to hear, thanks :)

**Comment by devzom** [comment]
> I was wrongly released the package. It's now fixed in 0.1.4.
> 
> Thanks for reporting 🙏


Great to hear, thanks :)
but don't see the 0.1.4 release :>

**Comment by tuarrep** [comment]
I see it on npm 🤔 

https://www.npmjs.com/package/nuxt-twa

**Comment by devzom** [comment]
> I see it on npm 🤔
> 
> https://www.npmjs.com/package/nuxt-twa

okey,  looked only here on GH and documentation 👍🏻 now it's in release 
thanks!
